# Generated by Django 3.0.6 on 2020-05-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0003_auto_20200516_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmark_date',
        ),
    ]
