# Generated by Django 3.0.6 on 2020-05-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0005_customerbookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbookmark',
            name='bookmark_id',
        ),
        migrations.RemoveField(
            model_name='customerbookmark',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customerbookmark',
            name='customer_bookmark_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
