# Generated by Django 3.0.6 on 2020-05-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0007_auto_20200517_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbookmark',
            name='customer_bookmark_id',
        ),
        migrations.AddField(
            model_name='customerbookmark',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerbookmark',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerbookmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
