# Generated by Django 3.0.6 on 2020-05-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0008_auto_20200517_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbookmark',
            name='bookmark_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
