# Generated by Django 3.0.6 on 2020-05-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0009_customerbookmark_bookmark_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='customer_bookmark',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_bookmark',
        ),
        migrations.AddField(
            model_name='customerbookmark',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='bookmark_app.Bookmark'),
        ),
        migrations.AddField(
            model_name='customerbookmark',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookmark_app.Customer'),
        ),
    ]
