# Generated by Django 3.0.6 on 2020-05-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0010_auto_20200517_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbookmark',
            name='bookmark_name',
        ),
    ]
