# Generated by Django 3.0.6 on 2020-05-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0011_remove_customerbookmark_bookmark_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbookmark',
            name='bookmark',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='bookmark_app.Bookmark'),
        ),
        migrations.AlterField(
            model_name='customerbookmark',
            name='customer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookmark_app.Customer'),
        ),
    ]
