# Generated by Django 3.0.6 on 2020-05-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0012_auto_20200517_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbookmark',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='bookmark_app.Bookmark'),
        ),
        migrations.AlterField(
            model_name='customerbookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerbookmark',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookmark_app.Customer'),
        ),
    ]
